language: scala
sudo: required
dist: trusty
scala:
- 2.12.3
jdk:
- oraclejdk8
- openjdk8
script:
- mvn scoverage:report
addons:
  sauce_connect: true
after_success:
  - bash <(curl -s https://codecov.io/bash)
  
